config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/sessions',to: 'sessions#create',      via: 'post'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :microposts #,    only: [:create, :destroy]
  resources :users
  resources :parties

  get '/parties/:id/join', to: 'parties#join', as: 'join_party'
  get '/parties/:id/leave', to: 'parties#leave', as: 'leave_party'
  post '/parties/:id/updatestatus', to: 'parties#update_status', as: 'update_status_for_party'
  post '/parties/search', to: 'parties#search', as: 'search_parties'

end

app/models/party.rb
class Party < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :participate_ins, dependent: :destroy
  has_many :has_tags, dependent: :destroy

  has_many :users, through: :participate_ins
  has_many :tags, through: :has_tags

  validates :name,
            presence: true,
            length: {maximum: 50}

  validates :description,
            presence: true,
            length: {maximum: 50}

  validates :user_limit,
            presence: true

  after_initialize :do_this_after_initialize

  def do_this_after_initialize
    unless ended_at.nil?
      if ended_at < Time.now
        update_attributes(recruiting: false)
      end
    end
  end

  def distance(longitude, latitude)
    @_longitude = longitude if @_longitude.nil?
    @_latitude = latitude if @_latitude.nil?

    if @_longitude != longitude || @_latitude != latitude || @_distance.nil?
      @_distance = ((location_longitude-longitude)**2 + (location_latitude - latitude)**2)**0.5
    end
    @_longitude = longitude
    @_latitude = latitude
    @_distance
  end

  def leader!(user)
    if participate?(user)
      participate_ins.find_by(user_id: user.id).update(leader: true)
    end
  end

  def leader
    leader_info = participate_ins.find_by(leader: true)
    users.find_by(id: leader_info.user_id) if !leader_info.nil?
  end

  def participate!(user)
    if participate_ins.length < self.user_limit && !participate?(user)
      participate_ins.create!(user_id: user.id, leader: false)
    else
      false
    end
  end

  def participate?(user)
    !participate_ins.find_by(user_id: user.id).nil?
  end

  def leave!(user)
    participate_ins.find_by(user_id: user.id).destroy if participate?(user)
  end

  def message_count
    microposts.count(:user_id)
  end

  def as_json(options = {})
    participants = {}
    users.each do |user|
      participants[user.id] = user
    end

    res = super(options)
    res[:leader] = leader
    res[:participants] = participants
    res # return res
  end

end

app/controllers/parties_controller.rb
# coding: UTF-8

class PartiesController < ApplicationController
  before_action :set_party, only: [:show, :edit, :update, :destroy, :join, :leave]
  before_action :correct_user, only: [:show, :edit, :leave]

  def index
    @parties = Party.all
    @active_parties = Party.where recruiting: true
    @categories = [1, 1, 1, 1, 1, 1, 1, 1]
    # @searched_parties = sort_by_distance(0, 0)
    # @parties = Party.all
  end

  def sort_by_distance(longitude, latitude)
    sorted_list = []
    @active_parties.each do |p|
      sorted_list << p
    end
    sorted_list.sort_by! { |p| p.distance(latitude, longitude) }
  end

  def new
    @party = Party.new
  end

  def create
    param = party_params
    param[:recruiting] = true
    param[:ended_at] = Time.now + 60*60*24 #2시간

    @party = Party.new(param)
    if @party.save
      @party.participate!(current_user)
      @party.leader!(current_user)
      flash[:success] = "파티가 생성되었습니다!!"
      redirect_to @party
    else
      flash[:danger] = "오류가 발생했습니다."
      render 'new'
    end
  end

  def show
  end

  def join
    if @party.participate!(current_user)
      Micropost.new({party_id: @party.id, content: current_user.id.to_s + " joined"}).save
      flash[:success] = "파티에 가입되었습니다."
      redirect_to @party
    else
      flash[:danger] = "가입에 실패하였습니다."
      redirect_to party_path
    end
  end

  def leave
    wasLeader = @party.leader.id.equal?(current_user.id)

    if @party.leave!(current_user)
      if (@party.users.length == 0)
        @party.destroy!
        flash[:success] = "파티가 해체되었습니다."
      else
        @party.leader!(@party.users.first) if wasLeader
        Micropost.new({party_id: @party.id, content: current_user.id.to_s + " leaved"}).save
        flash[:success] = "파티를 탈퇴하였습니다."
      end
      redirect_to root_path
    else
      flash[:danger] = "탈퇴에 실패하였습니다. 잠시 후 다시 시도하세요."
      redirect_to @party
    end
  end

  def edit
  end

  def update
    param = party_params
    if param[:ended_at].nil?
      param[:ended_at]= Time.now + 60*60*24 #24시간
    end

    if @party.update(param)
      flash[:success] = "파티 정보가 수정되었습니다. "
      redirect_to @party
    else
      flash[:danger] = "오류가 발생했습니다."
      render 'edit'
    end
  end

  def update_status
    @party = Party.find(params[:id])
    @participate_info = current_user.participate_info(@party)
    if @participate_info.update(status_msg: params[:content])
      flash[:success] = "상태메세지가 수정되었습니다."
      redirect_to @party
    else
      flash[:danger] = "오류가 발생했습니다."
      redirect_to @party
    end
  end

  def destroy
    if @party.destroy
      flash[:success] = "파티가 해체되었습니다."
      redirect_to root_url
    end
  end


  def search
    @keyword = params[:keyword]
    category = params[:category]

    @categories = []
    if category.length == 8
      category_condition = ""
    else
      category_condition = " and ("
      category.each_key do |value|
        @categories[Integer(value)] = true
        category_condition << " category = " << value << " or "
      end
      category_condition << "category=8 )"
    end

    if @keyword.to_s.empty? && category.length == 8
      redirect_to parties_url
    else
      result = []
      if @keyword.to_s.empty?
        result = Party.where(["recruiting = true" + category_condition])
      else
        @keyword.chomp.split(/,\s*/).each do |item|
          result = Party.where(["(name like ? or description like ? ) " + category_condition + " and recruiting = true", "%#{item}%", "%#{item}%"])
        end
      end

      @parties = Party.all
      @active_parties = result;
      render 'index'
    end
    # respond_to do |format|
    #   format.html { redirect_to parties_url, notice: 'result.' << result.as_json.to_s }
    #   format.json { result }
    # end
  end

  private
  def set_party
    @party = Party.find(params[:id])
  end

  def correct_user
    unless @party.participate?(current_user)
      flash[:danger] = "권한이 없습니다."
      redirect_to root_url
    end
  end

  def party_params
    params.require(:party).permit(:name, :user_limit, :category, :description, :location_longitude, :location_latitude, :recruiting, :ended_at)
  end
end

app/helpers/parties_helper.rb
# coding: UTF-8

module PartiesHelper
  def category_list
    ['취미', '운동', '식사', '스터디', '공연', '영화', '봉사', '기타']
  end

  def print_remaining_time(ended_at)
    unless ended_at.nil?
      remaining = (ended_at - Time.now)/60 + 0.5
      if remaining >= 60
        (remaining/60).to_i.to_s << "시간 " << (remaining%60).to_i.to_s << "분"
      else
        remaining.to_i.to_s << "분"
      end
    end
  end
end

app/views/parties/_participants_list_block.html.erb
<div class="mybox">
  <h3>
    파티 구성원
  </h3>
  <br>

  <% if @party.users.length > 0 %>
      <% @party.users.each do |user| %>
          <div class="center-block message_board" style="min-height:60px; margin-bottom: 8px; display: block">
            <a href="<%= user_path(user) %>">
              <%= gravatar_for user, {size: 48, style: "margin-right:8px;"} %>
            </a>

            <!--유저 이름, 파티장일시 아이콘 출력-->
            <p style="margin-bottom: 2px">
              <strong><%= link_to user.name, user %></strong>
              <% if @party.leader.id.equal?(user.id) %>
                  <span class="glyphicon glyphicon-star" style="font-size: 13px; color:#f0ad4e"></span>
              <% end %>
            </p>

            <!--유저일 시, 상태메세지 변경버튼 생성, -->
            <% if user.id.equal?(current_user.id) %>
                <a class="pull-right" href="#" data-toggle="modal" data-target="#bs-statusmsg-modal">
                  <span class="glyphicon glyphicon-pencil" style="font-size:12px; vertical-align: middle; padding-top: 2px; padding-right: 4px"></span>
                </a>
            <% end %>

            <!--상태메세지 보유 시 상태메세지 출력 -->
            <% if !user.status_msg(@party).blank? %>
                <p class="statusbox" style="margin-left: 54px">
                  <span ><%= user.status_msg(@party) %></span>
                </p>
            <% else
                 if user.id.equal? current_user.id %>
                    <p style="line-height: 2em; font-size: 13px; color:gray">상태메세지가 없습니다.</p>
                <% end end %>
          </div>
      <% end %>
  <% else %>
      <p>참여중인 파티원이 없습니다.</p>
  <% end %>
</div>


<!--modal (Bootstrap Dialog) -->
<div class="modal fade " id="bs-statusmsg-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm" style="margin-top: 30vh">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">상태메세지 수정</h4>
      </div>
      <% #@participate_info = current_user.participate_info(@party)  %>
      <% #form_for(@participate_info) do |f|  %>
      <form action="<%= update_status_for_party_path %>" method="post">
        <div style="display: none;">
          <input name="utf8" type="hidden" value="✓">
          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
        </div>
        <div class="modal-body">
          <label class="sr-only" for="inputStatusMessage">상태메세지를 입력하세요</label>
          <input name="content" type="text" class="form-control" id="inputStatusMessage" placeholder="상태메세지를 입력하세요." value="<%= current_user.status_msg(@party) %>" style="display: flex">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">닫기</button>
          <input type="submit" class="btn btn-primary" value="저장">
        </div>
      </form>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/parties/_party_info_block.html.erb
<div class="mybox">
  <h3>
    <p><%= @party.name %></p>
    <small><%= @party.description %></small>
    <p><small><%= category_list[@party.category] unless @party.category.nil? %></small></p>
  </h3>
  <br>
  <style type="text/css">
      dt {
          width: 100px !important;
          float: left;
      }

      dd {
          margin-left: 100px !important;
          padding-top: 1px;
      }
  </style>
  <dl>
    <dt>파티장</dt>
    <dd><%= @party.leader.name %></dd>

    <dt>개설일</dt>
    <dd><%= @party.created_at.strftime("%F") %></dd>

    <dt>파티원 수</dt>
    <dd><%= pluralize(@party.users.count, "user") %></dd>

    <dt>게시글 수</dt>
    <dd><%= pluralize(@party.message_count, "post") %></dd>

    <% if @party.recruiting? %>
        <dt>남은 시간</dt>
        <dd><%= print_remaining_time(@party.ended_at) %></dd>
    <% end %>

  </dl>

  <p></p>

  <% disable = "disabled" if !@party.leader.id.equal? current_user.id %>
  <p align="center">
    <%= form_for(@party) do |f| %>
        <% if @party.recruiting? %>
            <%= f.hidden_field :recruiting, value: false %>
            <%= f.submit "모집 중", class: "btn btn-success", style: "width:100%", method: :update, disabled: disable %>
        <% else %>
            <%= f.hidden_field :recruiting, value: true %>
            <%= f.submit "모집 시작", class: "btn btn-primary", style: "width:100%", method: :update, disabled: disable %>
        <% end %>
    <% end %>
  </p>

  <% if @party.leader.id.equal? current_user.id %>
      <p align="center">
        <%= link_to "정보 수정", edit_party_url(@party), class: "btn btn-default", style: "width:100%" %>
      </p>
  <% end %>
</div>

app/views/parties/_party_searching_block.erb
<form action="<%= search_parties_path %>" method="post">
  <div style="display: none;">
    <input name="utf8" type="hidden" value="✓">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  </div>
  <div>
    <p>
      <input name="keyword" type="text" class="form-control" placeholder="검색어를 입력하세요." style="display: flex">
    </p>
  </div>
  <div class="mybox">
    <h3>카테고리</h3>
    <hr>
    <p>

      <% i = 0 %>
      <% category_list.each do |category| %>
          <span style="width:24%; display: inline-block;"><input type="checkbox" name="category[<%= i %>]" <%= 'checked="checked"' if @categories[i] %> ><%= category %></span>
          <% i = i + 1 %>
      <% end %>
    </p>

  </div>
</form>

app/views/parties/create.html.erb
<h1>Party#create</h1>
<p>Find me in app/views/party/create.html.erb</p>

app/views/parties/edit.html.erb
<style type="text/css">
    body {
        overflow: hidden;
    }
</style>

<script type="text/javascript">

    var partyForm = '<%= escape_javascript render 'new_party_form' %>';

    function initialize() {

        var mapCenter = new google.maps.LatLng(parseFloat(<%=@party.location_latitude%>), parseFloat(<%=@party.location_longitude%>));
        drawMap(mapCenter, function () {
            createMarker(mapCenter, 'Edit Party', partyForm, true, true, true, null, true);
        });

    }
</script>

<!--google map api-->
<%= render 'mapjs' %>

<!--google map canvas-->
<div class="container-fluid" id="map-canvas" style="height: 100vh">

</div>

app/views/parties/index.html.erb
<style type="text/css">
    body {
        overflow: hidden;
    }
</style>

<script type="text/javascript">
    var parties = <%= raw @active_parties.to_json %>;
    var markers = new Object();

    //        var parties = [
    //            {"id": 16, "name": "a", "description": "dfads", "user_limit": 2, "location_longitude": null, "location_latitude": null, "recruiting": null, "created_at": "2014-05-29T10:17:12.000Z", "updated_at": "2014-05-29T10:17:12.000Z"},
    //            {"id": 18, "name": "dgdasg", "description": "dgasgd", "user_limit": 2, "location_longitude": null, "location_latitude": null, "recruiting": null, "created_at": "2014-05-29T10:52:19.000Z", "updated_at": "2014-05-29T10:52:19.000Z"},
    //            {"id": 19, "name": "이민준파티", "description": "fFSAD", "user_limit": 2, "location_longitude": null, "location_latitude": null, "recruiting": null, "created_at": "2014-05-29T10:52:55.000Z", "updated_at": "2014-05-29T10:52:55.000Z"},
    //            {"id": 20, "name": "g", "description": "hhh", "user_limit": 2, "location_longitude": 127.043, "location_latitude": 37.2792, "recruiting": null, "created_at": "2014-05-30T02:26:11.000Z", "updated_at": "2014-05-30T02:26:11.000Z"},
    //            {"id": 21, "name": "ggg", "description": "g", "user_limit": 2, "location_longitude": 127.035, "location_latitude": 37.2806, "recruiting": null, "created_at": "2014-05-30T02:28:06.000Z", "updated_at": "2014-05-30T02:28:06.000Z"},
    //            {"id": 22, "name": "sdbadadsb", "description": "afsafsa", "user_limit": 2, "location_longitude": 127.048, "location_latitude": 37.2943, "recruiting": null, "created_at": "2014-05-31T00:33:39.000Z", "updated_at": "2014-05-31T00:33:39.000Z"}
    //        ];

    function bringWindowToTop(id) {
        var marker = markers[id];
        marker.infowindow.setZIndex(zIndex++);
        var div = $("#party_" + id + "_content").trigger("create");
//        marker.infowindow.open(map, marker);
    }

    function togglePartyDescription(id) {

        var marker = markers[id];
        var div = $("#party_" + id + "_content");

        if (div.is(":visible")) {
            div.hide();
            marker.zIndex--;
            marker.infowindow.zIndex--;
            marker.infowindow.open(map, marker);
        } else {
            div.show();
            marker.setZIndex(zIndex++);
            marker.infowindow.setZIndex(zIndex++);
            marker.infowindow.open(map, marker);
        }
    }

    function collapseAllInfowindows() {
        for (var i in parties) {
            var party = parties[i];
            var marker = markers[party.id];
            marker.infowindow.close();
        }
    }

    function expandAllInfowindows() {
//        var beforeCenter = map.getCenter();
        for (var i in parties) {
            var party = parties[i];
            var marker = markers[party.id];
            if(map.getBounds().contains(marker.getPosition())) {
                marker.infowindow.open(map, marker);
//                map.panTo(beforeCenter);
            }
        }
    }

    var zIndex = 1;
    function setFocus(id) {
        var marker = markers[id];
        if(marker) {
            if (marker.infowindow) {
                marker.infowindow.open(map, marker);
                var div = $("#party_" + id + "_content");

                if (div) {
                    div.show();
                    marker.setZIndex(zIndex);
                    marker.infowindow.setZIndex(zIndex);
//                    marker.infowindow.open(map, marker);
                    map.panTo(marker.getPosition());
                    zIndex++;
                }
            }
        }
    }

    var beforeZoom = 14;
    var beforeCenter;
    function initialize() {

        var mapCenter = new google.maps.LatLng(parseFloat(37.28374147476122), parseFloat(127.04418));

        drawMap(mapCenter, function () {

            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    mapCenter = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                    map.setCenter(mapCenter);
                }, function () {
                    handleNoGeolocation(true);
                });
            } else {
                handleNoGeolocation(false);
            }

            for (var i in parties) {

                var party = parties[i];
                var remaining = (new Date(party.ended_at) - new Date()) / 60 / 1000;
                var remain_string = "";
                if (remaining > 60) remain_string = (remaining / 60 - 0.5).toFixed(0) + '시간';
                if (remaining % 60 > 0) remain_string = remain_string + ' ' + (remaining % 60 - 0.5).toFixed(0) + '분';

                var position = new google.maps.LatLng(parseFloat(party.location_latitude), parseFloat(party.location_longitude));
                var title = '<div class="partytitle" onclick="togglePartyDescription(' + party.id + ')">' + party.name + ' <span class="pull-right"><small>(' + Object.keys(party.participants).length + '/' + party.user_limit + ')</small></span></div>';
                var content = '<div id="party_' + party.id + '_content" style="display:none;" onclick="bringWindowToTop(' + party.id + ')">'
                        + '<p>' + '<img src="https://secure.gravatar.com/avatar/' + party.leader.hash + '?s=28&d=mm" style="margin-right:10px">'
                        + '<strong>' + party.leader.name + '</strong><span class="pull-right">see more</span></p>'
                        + '<p>' + party.description + '<span class="pull-right">' + remain_string + '</span></p>'
                        + '<div style="display:block; height: 32px">';

                if (party.participants[<%= current_user.id %>] != null) {
                    content += '<span style="display:inline-block; position:absolute; bottom:6px; color:darkgray"><a href="parties/' + party.id + '">들어가기</a></span>';
                } else {

                    if (Object.keys(party.participants).length < party.user_limit) {
                        content += '<a href="parties/' + party.id + '/join#" role="button" class="btn btn-success" style="margin-right:10px">가입</a>';
                    } else {
                        content += '<span style="display:inline-block; position:absolute; bottom:6px; color:darkgray">허용인원을 초과하였습니다.</span>';
                    }
                }

                content += '<button type="button" class="btn btn-default pull-right" onclick="togglePartyDescription(' + party.id + ')">닫기</button>'
                        + '</div>'
                        + '</div>';

                markers[party.id] = createMarker(position, title, content, true, false, true, 'http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=' + party.id + '|FF0000|000000', false);
            }


            google.maps.event.addListener(map, 'zoom_changed', function () {
                var zoomLevel = map.getZoom();
                if (beforeZoom > zoomLevel && zoomLevel <= 14) collapseAllInfowindows();
                else if (beforeZoom < zoomLevel && zoomLevel > 14) expandAllInfowindows();
                beforeZoom = zoomLevel;
            });

        });
    }
</script>

<!--google map api-->
<%= render 'mapjs' %>

<div class="container-fluid" style="height: 100vh; ">
  <div class="row">
    <div class="col-md-3" style="margin-top:20px;">
      <!--검색 폼-->
      <%= render 'party_searching_block' %>
      <!--검색 폼 끝-->

      <!--파티 목록-->
      <%= render 'party_listing_block' %>
      <!--파티 목록 끝-->
    </div>

    <div class="col-md-9" style="padding:0px;">
      <!--google map canvas-->
      <div id="map-canvas" style="height: 100vh"></div>
    </div>
  </div>
</div>

<% provide(:title, 'Listing parties') %>
<div class="container">
  <h1>Listing parties</h1>

  <table class="table">
    <thead>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th>User limit</th>
      <th>users</th>
      <th>recruiting?</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @parties.each do |party| %>
        <tr>
          <td><%= party.id %></td>
          <td><%= party.name %></td>
          <td><%= party.description %></td>
          <td><%= party.location_latitude %>
            <br><%= party.location_longitude %></td>
          <td><%= party.user_limit %></td>
          <td>
            <% party.participate_ins.each do |participate| %>
                <% user = User.find_by(id: participate.user_id) %>
                <p>
                  <%= user.name if !user.nil? %>
                  <%= '탈퇴한 회원' if user.nil? %>
                  <%= '(방장)' if participate.leader %>
                </p>
            <% end %>
          </td>
          <td><%= party.recruiting %></td>

          <td><%= link_to 'Show', party %></td>
          <td><%= link_to 'Join', join_party_path(party) %></td>
          <td><%= link_to 'Edit', edit_party_path(party) %></td>
          <td><%= link_to 'Destroy', party, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Party', new_party_path %>
</div>

app/views/parties/show.html.erb
<% provide(:title, @party.name) %>
<div class="container" style="margin-top:20px;">
  <div clas="row">

    <div class="col-lg-3 col-md-4 ">
      <%= render 'party_info_block' %>
      <%= render 'participants_list_block' %>
      <%= link_to "파티 탈퇴", leave_party_url(@party.id), data: {confirm: '탈퇴하시겠습니까?'}, class: "btn btn-default hidden-xs hidden-sm", style: "width:100%; margin-bottom:24px" %>
    </div>

    <div class="col-lg-9 col-md-8 col-xs-push-0">
      <div class="mybox">
        <h3>활동</h3>
        <!--New Micropost Form-->
        <% @micropost = Micropost.new %>
        <%= form_for(@micropost) do |f| %>
            <% if @micropost.errors.any? %>
                <div id="error_explanation">
                  <h3><%= pluralize(@micropost.errors.count, "error") %> prohibited this user from being saved:</h3>

                  <ul>
                    <% @micropost.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <div class="form-group" id="new_micropost_form">
              <%= f.text_field :party_id, value: @party.id, class: "hidden", style: "display: none;" %>
              <%= f.text_area :content, placeholder: "What's going on?", rows: '4', class: "form-control", style: "resize: none; overflow:hidden;", id: "textarea" %>
              <%= f.submit "Submit", class: "btn btn-primary pull-right", style: "position:relative; top: -40px; right: 5px" %>
            </div>

        <% end %>

        <br>

        <!--Message Board-->
        <div class="message_board">
          <% if @party.microposts.length > 0 %>
              <% @party.microposts.each do |micropost| %>
                  <% if !micropost.user_id.nil? %>
                      <% user = User.find(micropost.user_id) %>
                      <% if !user.nil? %>
                          <div class="media">
                            <a class="pull-left" href="#">
                              <%= gravatar_for user, size: 48 %>
                              <!--<img class="media-object" style="width: 64px; height: 64px;" alt="64x64" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCI+PHJlY3QgZmlsbD0iI2VlZSIgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiAvPjx0ZXh0IHN0eWxlPSJmb250LWZhbWlseTogQXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7IGZvbnQtc2l6ZTogMTJweDsgZm9udC13ZWlnaHQ6IGJvbGQ7IGRvbWluYW50LWJhc2VsaW5lOiBjZW50cmFsOyBmaWxsOiAjYWFhOyIgdGV4dC1hbmNob3I9Im1pZGRsZSIgeD0iMzIiIHk9IjMyIj42NHg2NDwvdGV4dD48L3N2Zz4=" data-src="holder.js/64x64">-->
                            </a>

                            <div class="media-body">
                              <div class="micropost_controlbox pull-right">
                                <% if current_user.id.equal?(user.id) %>
                                    <%= link_to micropost, method: :delete, data: {confirm: 'Are you sure?'} do %>
                                        <span class="glyphicon glyphicon-trash" style="font-size: 12px"></span>
                                    <% end %>
                                <% end %>
                              </div>

                              <h4 class="media-heading"><%= link_to user.name, user %></h4>
                              <%= micropost.content.gsub(/\n\r/, "<br />") %>

                              <span class="pull-right" style="margin-top: 10px">
                            <%= show_timestamp(micropost) %>
                            </span>
                            </div>
                          </div>
                      <% end %>
                  <% else %>
                      <% user = User.find_by_id(micropost.content.split[0]) %>
                      <% if !user.nil? %>
                          <div class="media-body info-message">
                            <span class="glyphicon glyphicon-user" style="font-size: 12px; color:steelblue"></span>
                            <%= link_to user.name, user %> 님이
                            <%= "파티에 가입하였습니다." if micropost.content.split[1].eql?("joined") %>
                            <%= "파티를 탈퇴하였습니다." if micropost.content.split[1].eql?("leaved") %>
                            <span class="pull-right date"><%= show_timestamp(micropost) %></span>
                          </div>
                      <% end %>
                  <% end %>
              <% end %>
          <% else %>
              <div class="media-body info-message">
                등록된 게시글이 없습니다.
              </div>
          <% end %>

          <div class="media-body info-message">
            <span class="glyphicon glyphicon-ok" style="font-size: 12px; color:steelblue"></span>
            파티가 생성되었습니다.
            <span class="pull-right date"><%= show_timestamp(@party) %></span>
          </div>

        </div>
      </div>

      <%= link_to "파티 탈퇴", leave_party_url(@party.id), data: {confirm: '탈퇴하시겠습니까?'}, class: "btn btn-default visible-xs visible-sm", style: "width:100%; margin-bottom:24px" %>

    </div>


  </div>
</div>