config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/sessions',to: 'sessions#create',      via: 'post'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :microposts #,    only: [:create, :destroy]
  resources :users
  resources :parties

  get '/parties/:id/join', to: 'parties#join', as: 'join_party'
  get '/parties/:id/leave', to: 'parties#leave', as: 'leave_party'
  post '/parties/:id/updatestatus', to: 'parties#update_status', as: 'update_status_for_party'
  post '/parties/search', to: 'parties#search', as: 'search_parties'

end

app/controllers/static_pages_controller.rb
# coding: UTF-8

class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @user = current_user
      @parties = @user.parties
      render 'dashboard'
    else
      render 'home'
    end
  end

  def help
  end

  def about
  end

end

app/helpers/static_pages_helper.rb
# coding: UTF-8

module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<div class="jumbotron">
  <div class="container">
    <h1 class="text-center">About</h1>

    <p>
      파티모집 서비스<br>
      사회에서의 수동적이고 소극적, 번거로운 모임 형성 과정에서 벗어나,<br>
      게임과 같은 능동적이고 적극적인 간편한 파티 형성을 추구한 서비스입니다.
    </p>

  </div>
</div>
<div class="container">
  <%= link_to "Back", :back, class: "btn btn-default", role: "button" %>

</div>

app/views/static_pages/dashboard.html.erb
<% provide(:title, 'Home') %>
<div class="container" style="margin-top:20px;">
  <div clas="row">
    <div class="col-md-3">
      <%= render 'shared/user_info_block' %>
      <div class="hidden-xs">
        <%= render 'shared/party_list_block' %>
      </div>
    </div>

    <div class="col-md-9">
      <div class="mybox">
        <h3>Dashboard</h3>
        <hr>
        <div class="message_board">
          <% @parties.each do |party| %>
              <h3><%= link_to party.name, party %></h3>
              <% if party.microposts.length > 0 %>
                  <% micropost = party.microposts.first %>
                      <% if !micropost.user_id.nil? %>
                          <% user = User.find(micropost.user_id) %>
                          <% if !user.nil? %>
                              <div class="media">
                                <a class="pull-left" href="#">
                                  <%= gravatar_for user, size: 48 %>
                                  <!--<img class="media-object" style="width: 64px; height: 64px;" alt="64x64" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCI+PHJlY3QgZmlsbD0iI2VlZSIgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiAvPjx0ZXh0IHN0eWxlPSJmb250LWZhbWlseTogQXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7IGZvbnQtc2l6ZTogMTJweDsgZm9udC13ZWlnaHQ6IGJvbGQ7IGRvbWluYW50LWJhc2VsaW5lOiBjZW50cmFsOyBmaWxsOiAjYWFhOyIgdGV4dC1hbmNob3I9Im1pZGRsZSIgeD0iMzIiIHk9IjMyIj42NHg2NDwvdGV4dD48L3N2Zz4=" data-src="holder.js/64x64">-->
                                </a>

                                <div class="media-body">

                                  <h4 class="media-heading"><%= link_to user.name, user %></h4>
                                  <%= micropost.content.gsub(/\n\r/, "<br />") %>

                                  <span class="pull-right" style="margin-top: 10px">
                            <%= show_timestamp(micropost) %>
                            </span>
                                </div>
                              </div>
                          <% end %>
                      <% else %>
                          <% user = User.find(micropost.content.split[0]) %>
                          <% if !user.nil? %>
                              <div class="media-body info-message">
                                <span class="glyphicon glyphicon-user" style="font-size: 12px; color:steelblue"></span>
                                <%= link_to user.name, user %> 님이
                                <%= "파티에 가입하였습니다." if micropost.content.split[1].eql?("joined") %>
                                <%= "파티를 탈퇴하였습니다." if micropost.content.split[1].eql?("leaved") %>
                                <span class="pull-right date"><%= show_timestamp(micropost) %></span>
                              </div>
                          <% end %>
                      <% end %>
              <% else %>
                  <div class="media-body info-message">
                    등록된 게시글이 없습니다.
                  </div>
              <% end %>
          <% end %>
          <% if @parties.length == 0 %>
              <div class="media-body info-message">
                <p>가입한 파티가 없네요? 지금 새 파티를 찾아보세요!</p>
                <p><a class="btn btn-default" href="<%= parties_path %>" role="button">둘러보기 &raquo;</a></p>
              </div>
          <% end %>
        </div>


      </div>

    </div>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div class="jumbotron">
  <div class="container">
    <h1 class="text-center">Help</h1>

    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
    </p>

  </div>
</div>
<div class="container">
  <%= link_to "Back", :back, class: "btn btn-default", role: "button" %>

</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to the Party Recruit!</h1>

    <p>
      파티모집 서비스에 오신 것을 환영합니다. <br>
      손쉽게 원하는 파티를 모집하거나, 원하는 파티를 찾아 가입 해 보세요!
    </p>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-primary btn-lg", role: "button" %>
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2>About</h2>

      <p>사회에서의 수동적이고 소극적, 번거로운 모임 형성 과정에서 벗어나,
        게임과 같은 능동적이고 적극적인 간편한 파티 형성을 추구한 신개념 소셜 그룹 매칭 서비스입니다.
      <p><%= link_to "About", about_path, class: "btn btn-default", role: "button" %></p>
    </div>
    <div class="col-md-4">
      <h2>Help</h2>

      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
        condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.
        Donec
        sed odio dui. </p>

      <p><%= link_to "Help", help_path, class: "btn btn-default", role: "button" %></p>
    </div>
    <div class="col-md-4">
      <h2>Contact</h2>

      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
        condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.
        Donec
        sed odio dui. </p>

      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>