config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/sessions',to: 'sessions#create',      via: 'post'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :microposts #,    only: [:create, :destroy]
  resources :users
  resources :parties

  get '/parties/:id/join', to: 'parties#join', as: 'join_party'
  get '/parties/:id/leave', to: 'parties#leave', as: 'leave_party'
  post '/parties/:id/updatestatus', to: 'parties#update_status', as: 'update_status_for_party'
  post '/parties/search', to: 'parties#search', as: 'search_parties'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  belongs_to :party
  default_scope -> { order('created_at DESC') }

  validates :party_id,
            presence: true,
            length: {maximum: 50}

  validates :content,
            presence: true,
            length: {maximum: 200}

end

app/controllers/microposts_controller.rb
# coding: UTF-8

class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]
  # before_action :set_party, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:create, :edit, :update, :destroy]
  # before_action :correct_user, only: :destroy

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show

  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @params = micropost_params
    @params[:user_id] = current_user.id
    @micropost = Micropost.new(@params)

    if @micropost.save
      flash[:success] = "게시글을 작성하였습니다!"
      redirect_to :back
      # format.html { redirect_to :back, notice: 'Micropost was successfully created.' }
      # format.json { render :show, status: :created, location: @micropost }
    else
      flash[:danger] = "게시글 작성에 실패하였습니다."
      redirect_to :back
      # redirect_to party_path(@params[:party_id])
      # format.json { render json: @micropost.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    if @micropost.destroy
      flash[:success] = "게시글을 삭제하였습니다."
      redirect_to :back
    else
      flash[:danger] = "게시글 삭제에 실패하였습니다."
      redirect_to :back
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    def set_party
      @party = Party.find(params[:party_id])
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :party_id)
    end

end

app/helpers/microposts_helper.rb
# coding: UTF-8

module MicropostsHelper

end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Party</th>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.party_id %></td>
        <td><%= micropost.user_id %></td>
        <td><%= micropost.content %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>Party:</strong>
  <%= @micropost.party_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>