config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/sessions',to: 'sessions#create',      via: 'post'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :microposts #,    only: [:create, :destroy]
  resources :users
  resources :parties

  get '/parties/:id/join', to: 'parties#join', as: 'join_party'
  get '/parties/:id/leave', to: 'parties#leave', as: 'leave_party'
  post '/parties/:id/updatestatus', to: 'parties#update_status', as: 'update_status_for_party'
  post '/parties/search', to: 'parties#search', as: 'search_parties'

end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <p>&copy; 파티모집 2014</p>
    <% params[:current_user] = current_user.attributes if signed_in? %>
    <%= debug(params) if Rails.env.development? %>

  </footer>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <header>
        <%= link_to t('app_title'), root_path, class: "navbar-brand", id: "logo" %>
      </header>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">

      <% if controller_name != 'sessions' %>
          <% if !signed_in? %>
              <%= form_for(:session, url: sessions_path, :html => {:class => "navbar-form navbar-right"}) do |f| %>
                  <div class="form-group">
                    <%= f.text_field :email, placeholder: "Email", class: "form-control" %>
                  </div>

                  <div class="form-group">
                    <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
                  </div>

                  <div class="form-group">
                    <%= f.submit "Sign in", class: "btn btn-success" %>
                  </div>
              <% end %>
          <% else %>
              <ul class="nav navbar-nav">
                <li id="menu1"><%= link_to "내 파티", root_path %></li>
                <li id="menu2"><%= link_to "둘러보기", parties_path %></li>
                <li id="menu3"><%= link_to "모집하기", new_party_path %></li>
                <!--<#% if controller_name=='static_pages' %>-->
                    <!--<%#= content_for :li, %>-->
                <!--<#% end %>-->
              </ul>

              <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">계정 <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "내 정보", current_user %></li>
                    <li><%= link_to "로그아웃", signout_path, method: :delete %></li>
                    <li class="divider"></li>
                    <li><%= link_to "About", about_path %></li>
                  </ul>
                </li>
              </ul>

              <!--<form class="navbar-form navbar-right hidden-sm" role="search">-->
                <!--<div class="form-group">-->
                  <!--<input type="text" class="form-control" placeholder="Search">-->
                <!--</div>-->
                <!--<button type="submit" class="btn hidden">Submit</button>-->
              <!--</form>-->

          <% end %>
      <% end %>

    </div>
    <!--/.navbar-collapse -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>

<!--Navbar 헤더-->
<%= render 'layouts/header' %>

<!--Bootstrap Alert-->
<div class="container" style="position: absolute; z-index: 10; left: 0; right: 0;">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, class: "alert alert-#{key} alert-dismissable") do %>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="margin-right: 24px">&times;</button>
          <%= value %>
          <% flash.discard(key) %>
      <% end %>
      <script type="text/javascript">
          window.setTimeout(function () {
              var flash = $(".alert");
              flash.fadeOut(1000, function () {
                  flash.remove();
              });
          }, 3000);
      </script>
  <% end %>
</div>

<!--본문 영역-->
<%= yield %>

<hr>

<!--Footer-->
<%= render 'layouts/footer' %>

</body>
</html>